// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var survival2d = survival2d || {};

/**
 * @const
 * @namespace
 */
survival2d.flatbuffers = survival2d.flatbuffers || {};

/**
 * @enum {number}
 */
survival2d.flatbuffers.Color = {
  Red: 0,
  Green: 1,
  Blue: 2
};

/**
 * @enum {string}
 */
survival2d.flatbuffers.ColorName = {
  '0': 'Red',
  '1': 'Green',
  '2': 'Blue'
};

/**
 * @enum {number}
 */
survival2d.flatbuffers.Equipment = {
  NONE: 0,
  Weapon: 1
};

/**
 * @enum {string}
 */
survival2d.flatbuffers.EquipmentName = {
  '0': 'NONE',
  '1': 'Weapon'
};

/**
 * @constructor
 */
survival2d.flatbuffers.Vec3 = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.Vec3}
 */
survival2d.flatbuffers.Vec3.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.Vec3.prototype.x = function() {
  return this.bb.readFloat32(this.bb_pos);
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.Vec3.prototype.y = function() {
  return this.bb.readFloat32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.Vec3.prototype.z = function() {
  return this.bb.readFloat32(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @param {number} z
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.Vec3.createVec3 = function(builder, x, y, z) {
  builder.prep(4, 12);
  builder.writeFloat32(z);
  builder.writeFloat32(y);
  builder.writeFloat32(x);
  return builder.offset();
};

/**
 * @constructor
 */
survival2d.flatbuffers.Monster = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.Monster}
 */
survival2d.flatbuffers.Monster.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.Monster=} obj
 * @returns {survival2d.flatbuffers.Monster}
 */
survival2d.flatbuffers.Monster.getRootAsMonster = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.Monster).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.Monster=} obj
 * @returns {survival2d.flatbuffers.Monster}
 */
survival2d.flatbuffers.Monster.getSizePrefixedRootAsMonster = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.Monster).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {survival2d.flatbuffers.Vec3=} obj
 * @returns {survival2d.flatbuffers.Vec3|null}
 */
survival2d.flatbuffers.Monster.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new survival2d.flatbuffers.Vec3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.Monster.prototype.mana = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 150;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.Monster.prototype.hp = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 100;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
survival2d.flatbuffers.Monster.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @returns {number}
 */
survival2d.flatbuffers.Monster.prototype.inventory = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.Monster.prototype.inventoryLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint8Array}
 */
survival2d.flatbuffers.Monster.prototype.inventoryArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @returns {survival2d.flatbuffers.Color}
 */
survival2d.flatbuffers.Monster.prototype.color = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? /** @type {survival2d.flatbuffers.Color} */ (this.bb.readInt8(this.bb_pos + offset)) : survival2d.flatbuffers.Color.Blue;
};

/**
 * @param {number} index
 * @param {survival2d.flatbuffers.Weapon=} obj
 * @returns {survival2d.flatbuffers.Weapon}
 */
survival2d.flatbuffers.Monster.prototype.weapons = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? (obj || new survival2d.flatbuffers.Weapon).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.Monster.prototype.weaponsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {survival2d.flatbuffers.Equipment}
 */
survival2d.flatbuffers.Monster.prototype.equippedType = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? /** @type {survival2d.flatbuffers.Equipment} */ (this.bb.readUint8(this.bb_pos + offset)) : survival2d.flatbuffers.Equipment.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
survival2d.flatbuffers.Monster.prototype.equipped = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {number} index
 * @param {survival2d.flatbuffers.Vec3=} obj
 * @returns {survival2d.flatbuffers.Vec3}
 */
survival2d.flatbuffers.Monster.prototype.path = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 24);
  return offset ? (obj || new survival2d.flatbuffers.Vec3).__init(this.bb.__vector(this.bb_pos + offset) + index * 12, this.bb) : null;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.Monster.prototype.pathLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 24);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.Monster.prototype.time = function() {
  var offset = this.bb.__offset(this.bb_pos, 26);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.Monster.startMonster = function(builder) {
  builder.startObject(12);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
survival2d.flatbuffers.Monster.addPos = function(builder, posOffset) {
  builder.addFieldStruct(0, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} mana
 */
survival2d.flatbuffers.Monster.addMana = function(builder, mana) {
  builder.addFieldInt16(1, mana, 150);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} hp
 */
survival2d.flatbuffers.Monster.addHp = function(builder, hp) {
  builder.addFieldInt16(2, hp, 100);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
survival2d.flatbuffers.Monster.addName = function(builder, nameOffset) {
  builder.addFieldOffset(3, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} inventoryOffset
 */
survival2d.flatbuffers.Monster.addInventory = function(builder, inventoryOffset) {
  builder.addFieldOffset(5, inventoryOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.Monster.createInventoryVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
survival2d.flatbuffers.Monster.startInventoryVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.Color} color
 */
survival2d.flatbuffers.Monster.addColor = function(builder, color) {
  builder.addFieldInt8(6, color, survival2d.flatbuffers.Color.Blue);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} weaponsOffset
 */
survival2d.flatbuffers.Monster.addWeapons = function(builder, weaponsOffset) {
  builder.addFieldOffset(7, weaponsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.Monster.createWeaponsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
survival2d.flatbuffers.Monster.startWeaponsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.Equipment} equippedType
 */
survival2d.flatbuffers.Monster.addEquippedType = function(builder, equippedType) {
  builder.addFieldInt8(8, equippedType, survival2d.flatbuffers.Equipment.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} equippedOffset
 */
survival2d.flatbuffers.Monster.addEquipped = function(builder, equippedOffset) {
  builder.addFieldOffset(9, equippedOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} pathOffset
 */
survival2d.flatbuffers.Monster.addPath = function(builder, pathOffset) {
  builder.addFieldOffset(10, pathOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
survival2d.flatbuffers.Monster.startPathVector = function(builder, numElems) {
  builder.startVector(12, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} time
 */
survival2d.flatbuffers.Monster.addTime = function(builder, time) {
  builder.addFieldFloat64(11, time, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.Monster.endMonster = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
survival2d.flatbuffers.Monster.finishMonsterBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
survival2d.flatbuffers.Monster.finishSizePrefixedMonsterBuffer = function(builder, offset) {
  builder.finish(offset, undefined, true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 * @param {number} mana
 * @param {number} hp
 * @param {flatbuffers.Offset} nameOffset
 * @param {flatbuffers.Offset} inventoryOffset
 * @param {survival2d.flatbuffers.Color} color
 * @param {flatbuffers.Offset} weaponsOffset
 * @param {survival2d.flatbuffers.Equipment} equippedType
 * @param {flatbuffers.Offset} equippedOffset
 * @param {flatbuffers.Offset} pathOffset
 * @param {number} time
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.Monster.createMonster = function(builder, posOffset, mana, hp, nameOffset, inventoryOffset, color, weaponsOffset, equippedType, equippedOffset, pathOffset, time) {
  survival2d.flatbuffers.Monster.startMonster(builder);
  survival2d.flatbuffers.Monster.addPos(builder, posOffset);
  survival2d.flatbuffers.Monster.addMana(builder, mana);
  survival2d.flatbuffers.Monster.addHp(builder, hp);
  survival2d.flatbuffers.Monster.addName(builder, nameOffset);
  survival2d.flatbuffers.Monster.addInventory(builder, inventoryOffset);
  survival2d.flatbuffers.Monster.addColor(builder, color);
  survival2d.flatbuffers.Monster.addWeapons(builder, weaponsOffset);
  survival2d.flatbuffers.Monster.addEquippedType(builder, equippedType);
  survival2d.flatbuffers.Monster.addEquipped(builder, equippedOffset);
  survival2d.flatbuffers.Monster.addPath(builder, pathOffset);
  survival2d.flatbuffers.Monster.addTime(builder, time);
  return survival2d.flatbuffers.Monster.endMonster(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.Weapon = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.Weapon}
 */
survival2d.flatbuffers.Weapon.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.Weapon=} obj
 * @returns {survival2d.flatbuffers.Weapon}
 */
survival2d.flatbuffers.Weapon.getRootAsWeapon = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.Weapon).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.Weapon=} obj
 * @returns {survival2d.flatbuffers.Weapon}
 */
survival2d.flatbuffers.Weapon.getSizePrefixedRootAsWeapon = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.Weapon).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
survival2d.flatbuffers.Weapon.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.Weapon.prototype.damage = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.Weapon.startWeapon = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
survival2d.flatbuffers.Weapon.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} damage
 */
survival2d.flatbuffers.Weapon.addDamage = function(builder, damage) {
  builder.addFieldInt16(1, damage, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.Weapon.endWeapon = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 * @param {number} damage
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.Weapon.createWeapon = function(builder, nameOffset, damage) {
  survival2d.flatbuffers.Weapon.startWeapon(builder);
  survival2d.flatbuffers.Weapon.addName(builder, nameOffset);
  survival2d.flatbuffers.Weapon.addDamage(builder, damage);
  return survival2d.flatbuffers.Weapon.endWeapon(builder);
}

// Exports for Node.js and RequireJS
this.survival2d = survival2d;
