// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var survival2d = survival2d || {};

/**
 * @const
 * @namespace
 */
survival2d.flatbuffers = survival2d.flatbuffers || {};

/**
 * @enum {number}
 */
survival2d.flatbuffers.GunTypeEnum = {
  NORMAL: 0
};

/**
 * @enum {string}
 */
survival2d.flatbuffers.GunTypeEnumName = {
  '0': 'NORMAL'
};

/**
 * @enum {number}
 */
survival2d.flatbuffers.BulletTypeEnum = {
  NORMAL: 0
};

/**
 * @enum {string}
 */
survival2d.flatbuffers.BulletTypeEnumName = {
  '0': 'NORMAL'
};

/**
 * @enum {number}
 */
survival2d.flatbuffers.VestTypeEnum = {
  LEVEL_0: 0,
  LEVEL_1: 1
};

/**
 * @enum {string}
 */
survival2d.flatbuffers.VestTypeEnumName = {
  '0': 'LEVEL_0',
  '1': 'LEVEL_1'
};

/**
 * @enum {number}
 */
survival2d.flatbuffers.HelmetTypeEnum = {
  LEVEL_0: 0,
  LEVEL_1: 1
};

/**
 * @enum {string}
 */
survival2d.flatbuffers.HelmetTypeEnumName = {
  '0': 'LEVEL_0',
  '1': 'LEVEL_1'
};

/**
 * @enum {number}
 */
survival2d.flatbuffers.BackPackTypeEnum = {
  LEVEL_0: 0,
  LEVEL_1: 1,
  LEVEL_2: 2
};

/**
 * @enum {string}
 */
survival2d.flatbuffers.BackPackTypeEnumName = {
  '0': 'LEVEL_0',
  '1': 'LEVEL_1',
  '2': 'LEVEL_2'
};

/**
 * @enum {number}
 */
survival2d.flatbuffers.ItemUnion = {
  NONE: 0,
  BulletItemTable: 1,
  GunItemTable: 2,
  VestItemTable: 3,
  HelmetItemTable: 4,
  BandageItemTable: 5,
  MedKitItemTable: 6,
  BackPackItemTable: 7
};

/**
 * @enum {string}
 */
survival2d.flatbuffers.ItemUnionName = {
  '0': 'NONE',
  '1': 'BulletItemTable',
  '2': 'GunItemTable',
  '3': 'VestItemTable',
  '4': 'HelmetItemTable',
  '5': 'BandageItemTable',
  '6': 'MedKitItemTable',
  '7': 'BackPackItemTable'
};

/**
 * @enum {number}
 */
survival2d.flatbuffers.MapObjectUnion = {
  NONE: 0,
  BulletItemTable: 1,
  GunItemTable: 2,
  VestItemTable: 3,
  HelmetItemTable: 4,
  BandageItemTable: 5,
  MedKitItemTable: 6,
  BackPackItemTable: 7,
  TreeTable: 8,
  ContainerTable: 9,
  StoneTable: 10,
  WallTable: 11
};

/**
 * @enum {string}
 */
survival2d.flatbuffers.MapObjectUnionName = {
  '0': 'NONE',
  '1': 'BulletItemTable',
  '2': 'GunItemTable',
  '3': 'VestItemTable',
  '4': 'HelmetItemTable',
  '5': 'BandageItemTable',
  '6': 'MedKitItemTable',
  '7': 'BackPackItemTable',
  '8': 'TreeTable',
  '9': 'ContainerTable',
  '10': 'StoneTable',
  '11': 'WallTable'
};

/**
 * @enum {number}
 */
survival2d.flatbuffers.WeaponUnion = {
  NONE: 0,
  HandTable: 1,
  GunTable: 2
};

/**
 * @enum {string}
 */
survival2d.flatbuffers.WeaponUnionName = {
  '0': 'NONE',
  '1': 'HandTable',
  '2': 'GunTable'
};

/**
 * @enum {number}
 */
survival2d.flatbuffers.ErrorEnum = {
  SUCCESS: 0,
  NOT_FOUND_YET: 1,
  FAILURE: 2
};

/**
 * @enum {string}
 */
survival2d.flatbuffers.ErrorEnumName = {
  '0': 'SUCCESS',
  '1': 'NOT_FOUND_YET',
  '2': 'FAILURE'
};

/**
 * @constructor
 */
survival2d.flatbuffers.Vector2Struct = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.Vector2Struct}
 */
survival2d.flatbuffers.Vector2Struct.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.Vector2Struct.prototype.x = function() {
  return this.bb.readFloat32(this.bb_pos);
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.Vector2Struct.prototype.y = function() {
  return this.bb.readFloat32(this.bb_pos + 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.Vector2Struct.createVector2Struct = function(builder, x, y) {
  builder.prep(4, 8);
  builder.writeFloat32(y);
  builder.writeFloat32(x);
  return builder.offset();
};

/**
 * @constructor
 */
survival2d.flatbuffers.CircleStruct = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.CircleStruct}
 */
survival2d.flatbuffers.CircleStruct.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.CircleStruct.prototype.x = function() {
  return this.bb.readFloat32(this.bb_pos);
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.CircleStruct.prototype.y = function() {
  return this.bb.readFloat32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.CircleStruct.prototype.radius = function() {
  return this.bb.readFloat32(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @param {number} radius
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.CircleStruct.createCircleStruct = function(builder, x, y, radius) {
  builder.prep(4, 12);
  builder.writeFloat32(radius);
  builder.writeFloat32(y);
  builder.writeFloat32(x);
  return builder.offset();
};

/**
 * @constructor
 */
survival2d.flatbuffers.PlayerTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.PlayerTable}
 */
survival2d.flatbuffers.PlayerTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PlayerTable=} obj
 * @returns {survival2d.flatbuffers.PlayerTable}
 */
survival2d.flatbuffers.PlayerTable.getRootAsPlayerTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.PlayerTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PlayerTable=} obj
 * @returns {survival2d.flatbuffers.PlayerTable}
 */
survival2d.flatbuffers.PlayerTable.getSizePrefixedRootAsPlayerTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.PlayerTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.PlayerTable.prototype.playerId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {survival2d.flatbuffers.Vector2Struct=} obj
 * @returns {survival2d.flatbuffers.Vector2Struct|null}
 */
survival2d.flatbuffers.PlayerTable.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new survival2d.flatbuffers.Vector2Struct).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.PlayerTable.prototype.rotation = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.PlayerTable.prototype.team = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.PlayerTable.startPlayerTable = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} playerId
 */
survival2d.flatbuffers.PlayerTable.addPlayerId = function(builder, playerId) {
  builder.addFieldInt32(0, playerId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
survival2d.flatbuffers.PlayerTable.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(1, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} rotation
 */
survival2d.flatbuffers.PlayerTable.addRotation = function(builder, rotation) {
  builder.addFieldFloat32(2, rotation, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} team
 */
survival2d.flatbuffers.PlayerTable.addTeam = function(builder, team) {
  builder.addFieldInt32(3, team, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PlayerTable.endPlayerTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} playerId
 * @param {flatbuffers.Offset} positionOffset
 * @param {number} rotation
 * @param {number} team
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PlayerTable.createPlayerTable = function(builder, playerId, positionOffset, rotation, team) {
  survival2d.flatbuffers.PlayerTable.startPlayerTable(builder);
  survival2d.flatbuffers.PlayerTable.addPlayerId(builder, playerId);
  survival2d.flatbuffers.PlayerTable.addPosition(builder, positionOffset);
  survival2d.flatbuffers.PlayerTable.addRotation(builder, rotation);
  survival2d.flatbuffers.PlayerTable.addTeam(builder, team);
  return survival2d.flatbuffers.PlayerTable.endPlayerTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.TreeTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.TreeTable}
 */
survival2d.flatbuffers.TreeTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.TreeTable=} obj
 * @returns {survival2d.flatbuffers.TreeTable}
 */
survival2d.flatbuffers.TreeTable.getRootAsTreeTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.TreeTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.TreeTable=} obj
 * @returns {survival2d.flatbuffers.TreeTable}
 */
survival2d.flatbuffers.TreeTable.getSizePrefixedRootAsTreeTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.TreeTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.TreeTable.startTreeTable = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.TreeTable.endTreeTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.TreeTable.createTreeTable = function(builder) {
  survival2d.flatbuffers.TreeTable.startTreeTable(builder);
  return survival2d.flatbuffers.TreeTable.endTreeTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.ContainerTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.ContainerTable}
 */
survival2d.flatbuffers.ContainerTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.ContainerTable=} obj
 * @returns {survival2d.flatbuffers.ContainerTable}
 */
survival2d.flatbuffers.ContainerTable.getRootAsContainerTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.ContainerTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.ContainerTable=} obj
 * @returns {survival2d.flatbuffers.ContainerTable}
 */
survival2d.flatbuffers.ContainerTable.getSizePrefixedRootAsContainerTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.ContainerTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.ContainerTable.startContainerTable = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.ContainerTable.endContainerTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.ContainerTable.createContainerTable = function(builder) {
  survival2d.flatbuffers.ContainerTable.startContainerTable(builder);
  return survival2d.flatbuffers.ContainerTable.endContainerTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.StoneTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.StoneTable}
 */
survival2d.flatbuffers.StoneTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.StoneTable=} obj
 * @returns {survival2d.flatbuffers.StoneTable}
 */
survival2d.flatbuffers.StoneTable.getRootAsStoneTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.StoneTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.StoneTable=} obj
 * @returns {survival2d.flatbuffers.StoneTable}
 */
survival2d.flatbuffers.StoneTable.getSizePrefixedRootAsStoneTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.StoneTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.StoneTable.startStoneTable = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.StoneTable.endStoneTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.StoneTable.createStoneTable = function(builder) {
  survival2d.flatbuffers.StoneTable.startStoneTable(builder);
  return survival2d.flatbuffers.StoneTable.endStoneTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.WallTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.WallTable}
 */
survival2d.flatbuffers.WallTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.WallTable=} obj
 * @returns {survival2d.flatbuffers.WallTable}
 */
survival2d.flatbuffers.WallTable.getRootAsWallTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.WallTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.WallTable=} obj
 * @returns {survival2d.flatbuffers.WallTable}
 */
survival2d.flatbuffers.WallTable.getSizePrefixedRootAsWallTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.WallTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.WallTable.startWallTable = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.WallTable.endWallTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.WallTable.createWallTable = function(builder) {
  survival2d.flatbuffers.WallTable.startWallTable(builder);
  return survival2d.flatbuffers.WallTable.endWallTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.GunItemTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.GunItemTable}
 */
survival2d.flatbuffers.GunItemTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.GunItemTable=} obj
 * @returns {survival2d.flatbuffers.GunItemTable}
 */
survival2d.flatbuffers.GunItemTable.getRootAsGunItemTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.GunItemTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.GunItemTable=} obj
 * @returns {survival2d.flatbuffers.GunItemTable}
 */
survival2d.flatbuffers.GunItemTable.getSizePrefixedRootAsGunItemTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.GunItemTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {survival2d.flatbuffers.GunTypeEnum}
 */
survival2d.flatbuffers.GunItemTable.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {survival2d.flatbuffers.GunTypeEnum} */ (this.bb.readInt8(this.bb_pos + offset)) : survival2d.flatbuffers.GunTypeEnum.NORMAL;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.GunItemTable.prototype.numBullet = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.GunItemTable.startGunItemTable = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.GunTypeEnum} type
 */
survival2d.flatbuffers.GunItemTable.addType = function(builder, type) {
  builder.addFieldInt8(0, type, survival2d.flatbuffers.GunTypeEnum.NORMAL);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numBullet
 */
survival2d.flatbuffers.GunItemTable.addNumBullet = function(builder, numBullet) {
  builder.addFieldInt32(1, numBullet, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.GunItemTable.endGunItemTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.GunTypeEnum} type
 * @param {number} numBullet
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.GunItemTable.createGunItemTable = function(builder, type, numBullet) {
  survival2d.flatbuffers.GunItemTable.startGunItemTable(builder);
  survival2d.flatbuffers.GunItemTable.addType(builder, type);
  survival2d.flatbuffers.GunItemTable.addNumBullet(builder, numBullet);
  return survival2d.flatbuffers.GunItemTable.endGunItemTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.BulletItemTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.BulletItemTable}
 */
survival2d.flatbuffers.BulletItemTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.BulletItemTable=} obj
 * @returns {survival2d.flatbuffers.BulletItemTable}
 */
survival2d.flatbuffers.BulletItemTable.getRootAsBulletItemTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.BulletItemTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.BulletItemTable=} obj
 * @returns {survival2d.flatbuffers.BulletItemTable}
 */
survival2d.flatbuffers.BulletItemTable.getSizePrefixedRootAsBulletItemTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.BulletItemTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {survival2d.flatbuffers.BulletTypeEnum}
 */
survival2d.flatbuffers.BulletItemTable.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {survival2d.flatbuffers.BulletTypeEnum} */ (this.bb.readInt8(this.bb_pos + offset)) : survival2d.flatbuffers.BulletTypeEnum.NORMAL;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.BulletItemTable.prototype.numBullet = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.BulletItemTable.startBulletItemTable = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.BulletTypeEnum} type
 */
survival2d.flatbuffers.BulletItemTable.addType = function(builder, type) {
  builder.addFieldInt8(0, type, survival2d.flatbuffers.BulletTypeEnum.NORMAL);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numBullet
 */
survival2d.flatbuffers.BulletItemTable.addNumBullet = function(builder, numBullet) {
  builder.addFieldInt32(1, numBullet, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.BulletItemTable.endBulletItemTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.BulletTypeEnum} type
 * @param {number} numBullet
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.BulletItemTable.createBulletItemTable = function(builder, type, numBullet) {
  survival2d.flatbuffers.BulletItemTable.startBulletItemTable(builder);
  survival2d.flatbuffers.BulletItemTable.addType(builder, type);
  survival2d.flatbuffers.BulletItemTable.addNumBullet(builder, numBullet);
  return survival2d.flatbuffers.BulletItemTable.endBulletItemTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.VestItemTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.VestItemTable}
 */
survival2d.flatbuffers.VestItemTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.VestItemTable=} obj
 * @returns {survival2d.flatbuffers.VestItemTable}
 */
survival2d.flatbuffers.VestItemTable.getRootAsVestItemTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.VestItemTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.VestItemTable=} obj
 * @returns {survival2d.flatbuffers.VestItemTable}
 */
survival2d.flatbuffers.VestItemTable.getSizePrefixedRootAsVestItemTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.VestItemTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {survival2d.flatbuffers.VestTypeEnum}
 */
survival2d.flatbuffers.VestItemTable.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {survival2d.flatbuffers.VestTypeEnum} */ (this.bb.readInt8(this.bb_pos + offset)) : survival2d.flatbuffers.VestTypeEnum.LEVEL_0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.VestItemTable.startVestItemTable = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.VestTypeEnum} type
 */
survival2d.flatbuffers.VestItemTable.addType = function(builder, type) {
  builder.addFieldInt8(0, type, survival2d.flatbuffers.VestTypeEnum.LEVEL_0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.VestItemTable.endVestItemTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.VestTypeEnum} type
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.VestItemTable.createVestItemTable = function(builder, type) {
  survival2d.flatbuffers.VestItemTable.startVestItemTable(builder);
  survival2d.flatbuffers.VestItemTable.addType(builder, type);
  return survival2d.flatbuffers.VestItemTable.endVestItemTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.HelmetItemTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.HelmetItemTable}
 */
survival2d.flatbuffers.HelmetItemTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.HelmetItemTable=} obj
 * @returns {survival2d.flatbuffers.HelmetItemTable}
 */
survival2d.flatbuffers.HelmetItemTable.getRootAsHelmetItemTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.HelmetItemTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.HelmetItemTable=} obj
 * @returns {survival2d.flatbuffers.HelmetItemTable}
 */
survival2d.flatbuffers.HelmetItemTable.getSizePrefixedRootAsHelmetItemTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.HelmetItemTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {survival2d.flatbuffers.HelmetTypeEnum}
 */
survival2d.flatbuffers.HelmetItemTable.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {survival2d.flatbuffers.HelmetTypeEnum} */ (this.bb.readInt8(this.bb_pos + offset)) : survival2d.flatbuffers.HelmetTypeEnum.LEVEL_0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.HelmetItemTable.startHelmetItemTable = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.HelmetTypeEnum} type
 */
survival2d.flatbuffers.HelmetItemTable.addType = function(builder, type) {
  builder.addFieldInt8(0, type, survival2d.flatbuffers.HelmetTypeEnum.LEVEL_0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.HelmetItemTable.endHelmetItemTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.HelmetTypeEnum} type
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.HelmetItemTable.createHelmetItemTable = function(builder, type) {
  survival2d.flatbuffers.HelmetItemTable.startHelmetItemTable(builder);
  survival2d.flatbuffers.HelmetItemTable.addType(builder, type);
  return survival2d.flatbuffers.HelmetItemTable.endHelmetItemTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.BandageItemTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.BandageItemTable}
 */
survival2d.flatbuffers.BandageItemTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.BandageItemTable=} obj
 * @returns {survival2d.flatbuffers.BandageItemTable}
 */
survival2d.flatbuffers.BandageItemTable.getRootAsBandageItemTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.BandageItemTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.BandageItemTable=} obj
 * @returns {survival2d.flatbuffers.BandageItemTable}
 */
survival2d.flatbuffers.BandageItemTable.getSizePrefixedRootAsBandageItemTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.BandageItemTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.BandageItemTable.startBandageItemTable = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.BandageItemTable.endBandageItemTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.BandageItemTable.createBandageItemTable = function(builder) {
  survival2d.flatbuffers.BandageItemTable.startBandageItemTable(builder);
  return survival2d.flatbuffers.BandageItemTable.endBandageItemTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.MedKitItemTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.MedKitItemTable}
 */
survival2d.flatbuffers.MedKitItemTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.MedKitItemTable=} obj
 * @returns {survival2d.flatbuffers.MedKitItemTable}
 */
survival2d.flatbuffers.MedKitItemTable.getRootAsMedKitItemTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.MedKitItemTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.MedKitItemTable=} obj
 * @returns {survival2d.flatbuffers.MedKitItemTable}
 */
survival2d.flatbuffers.MedKitItemTable.getSizePrefixedRootAsMedKitItemTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.MedKitItemTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.MedKitItemTable.startMedKitItemTable = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.MedKitItemTable.endMedKitItemTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.MedKitItemTable.createMedKitItemTable = function(builder) {
  survival2d.flatbuffers.MedKitItemTable.startMedKitItemTable(builder);
  return survival2d.flatbuffers.MedKitItemTable.endMedKitItemTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.BackPackItemTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.BackPackItemTable}
 */
survival2d.flatbuffers.BackPackItemTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.BackPackItemTable=} obj
 * @returns {survival2d.flatbuffers.BackPackItemTable}
 */
survival2d.flatbuffers.BackPackItemTable.getRootAsBackPackItemTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.BackPackItemTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.BackPackItemTable=} obj
 * @returns {survival2d.flatbuffers.BackPackItemTable}
 */
survival2d.flatbuffers.BackPackItemTable.getSizePrefixedRootAsBackPackItemTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.BackPackItemTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {survival2d.flatbuffers.BackPackTypeEnum}
 */
survival2d.flatbuffers.BackPackItemTable.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {survival2d.flatbuffers.BackPackTypeEnum} */ (this.bb.readInt8(this.bb_pos + offset)) : survival2d.flatbuffers.BackPackTypeEnum.LEVEL_0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.BackPackItemTable.startBackPackItemTable = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.BackPackTypeEnum} type
 */
survival2d.flatbuffers.BackPackItemTable.addType = function(builder, type) {
  builder.addFieldInt8(0, type, survival2d.flatbuffers.BackPackTypeEnum.LEVEL_0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.BackPackItemTable.endBackPackItemTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.BackPackTypeEnum} type
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.BackPackItemTable.createBackPackItemTable = function(builder, type) {
  survival2d.flatbuffers.BackPackItemTable.startBackPackItemTable(builder);
  survival2d.flatbuffers.BackPackItemTable.addType(builder, type);
  return survival2d.flatbuffers.BackPackItemTable.endBackPackItemTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.MapObjectTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.MapObjectTable}
 */
survival2d.flatbuffers.MapObjectTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.MapObjectTable=} obj
 * @returns {survival2d.flatbuffers.MapObjectTable}
 */
survival2d.flatbuffers.MapObjectTable.getRootAsMapObjectTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.MapObjectTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.MapObjectTable=} obj
 * @returns {survival2d.flatbuffers.MapObjectTable}
 */
survival2d.flatbuffers.MapObjectTable.getSizePrefixedRootAsMapObjectTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.MapObjectTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.MapObjectTable.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {survival2d.flatbuffers.Vector2Struct=} obj
 * @returns {survival2d.flatbuffers.Vector2Struct|null}
 */
survival2d.flatbuffers.MapObjectTable.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new survival2d.flatbuffers.Vector2Struct).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {survival2d.flatbuffers.MapObjectUnion}
 */
survival2d.flatbuffers.MapObjectTable.prototype.dataType = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {survival2d.flatbuffers.MapObjectUnion} */ (this.bb.readUint8(this.bb_pos + offset)) : survival2d.flatbuffers.MapObjectUnion.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
survival2d.flatbuffers.MapObjectTable.prototype.data = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.MapObjectTable.startMapObjectTable = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
survival2d.flatbuffers.MapObjectTable.addId = function(builder, id) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
survival2d.flatbuffers.MapObjectTable.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(1, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.MapObjectUnion} dataType
 */
survival2d.flatbuffers.MapObjectTable.addDataType = function(builder, dataType) {
  builder.addFieldInt8(2, dataType, survival2d.flatbuffers.MapObjectUnion.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 */
survival2d.flatbuffers.MapObjectTable.addData = function(builder, dataOffset) {
  builder.addFieldOffset(3, dataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.MapObjectTable.endMapObjectTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 * @param {flatbuffers.Offset} positionOffset
 * @param {survival2d.flatbuffers.MapObjectUnion} dataType
 * @param {flatbuffers.Offset} dataOffset
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.MapObjectTable.createMapObjectTable = function(builder, id, positionOffset, dataType, dataOffset) {
  survival2d.flatbuffers.MapObjectTable.startMapObjectTable(builder);
  survival2d.flatbuffers.MapObjectTable.addId(builder, id);
  survival2d.flatbuffers.MapObjectTable.addPosition(builder, positionOffset);
  survival2d.flatbuffers.MapObjectTable.addDataType(builder, dataType);
  survival2d.flatbuffers.MapObjectTable.addData(builder, dataOffset);
  return survival2d.flatbuffers.MapObjectTable.endMapObjectTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.BulletTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.BulletTable}
 */
survival2d.flatbuffers.BulletTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.BulletTable=} obj
 * @returns {survival2d.flatbuffers.BulletTable}
 */
survival2d.flatbuffers.BulletTable.getRootAsBulletTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.BulletTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.BulletTable=} obj
 * @returns {survival2d.flatbuffers.BulletTable}
 */
survival2d.flatbuffers.BulletTable.getSizePrefixedRootAsBulletTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.BulletTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.BulletTable.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {survival2d.flatbuffers.Vector2Struct=} obj
 * @returns {survival2d.flatbuffers.Vector2Struct|null}
 */
survival2d.flatbuffers.BulletTable.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new survival2d.flatbuffers.Vector2Struct).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {survival2d.flatbuffers.BulletTypeEnum}
 */
survival2d.flatbuffers.BulletTable.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {survival2d.flatbuffers.BulletTypeEnum} */ (this.bb.readInt8(this.bb_pos + offset)) : survival2d.flatbuffers.BulletTypeEnum.NORMAL;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.BulletTable.prototype.owner = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {survival2d.flatbuffers.Vector2Struct=} obj
 * @returns {survival2d.flatbuffers.Vector2Struct|null}
 */
survival2d.flatbuffers.BulletTable.prototype.direction = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new survival2d.flatbuffers.Vector2Struct).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.BulletTable.startBulletTable = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
survival2d.flatbuffers.BulletTable.addId = function(builder, id) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
survival2d.flatbuffers.BulletTable.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(1, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.BulletTypeEnum} type
 */
survival2d.flatbuffers.BulletTable.addType = function(builder, type) {
  builder.addFieldInt8(2, type, survival2d.flatbuffers.BulletTypeEnum.NORMAL);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} owner
 */
survival2d.flatbuffers.BulletTable.addOwner = function(builder, owner) {
  builder.addFieldInt32(3, owner, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} directionOffset
 */
survival2d.flatbuffers.BulletTable.addDirection = function(builder, directionOffset) {
  builder.addFieldStruct(4, directionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.BulletTable.endBulletTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 * @param {flatbuffers.Offset} positionOffset
 * @param {survival2d.flatbuffers.BulletTypeEnum} type
 * @param {number} owner
 * @param {flatbuffers.Offset} directionOffset
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.BulletTable.createBulletTable = function(builder, id, positionOffset, type, owner, directionOffset) {
  survival2d.flatbuffers.BulletTable.startBulletTable(builder);
  survival2d.flatbuffers.BulletTable.addId(builder, id);
  survival2d.flatbuffers.BulletTable.addPosition(builder, positionOffset);
  survival2d.flatbuffers.BulletTable.addType(builder, type);
  survival2d.flatbuffers.BulletTable.addOwner(builder, owner);
  survival2d.flatbuffers.BulletTable.addDirection(builder, directionOffset);
  return survival2d.flatbuffers.BulletTable.endBulletTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.BulletWithQuantityTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.BulletWithQuantityTable}
 */
survival2d.flatbuffers.BulletWithQuantityTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.BulletWithQuantityTable=} obj
 * @returns {survival2d.flatbuffers.BulletWithQuantityTable}
 */
survival2d.flatbuffers.BulletWithQuantityTable.getRootAsBulletWithQuantityTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.BulletWithQuantityTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.BulletWithQuantityTable=} obj
 * @returns {survival2d.flatbuffers.BulletWithQuantityTable}
 */
survival2d.flatbuffers.BulletWithQuantityTable.getSizePrefixedRootAsBulletWithQuantityTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.BulletWithQuantityTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {survival2d.flatbuffers.BulletTypeEnum}
 */
survival2d.flatbuffers.BulletWithQuantityTable.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {survival2d.flatbuffers.BulletTypeEnum} */ (this.bb.readInt8(this.bb_pos + offset)) : survival2d.flatbuffers.BulletTypeEnum.NORMAL;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.BulletWithQuantityTable.prototype.num = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.BulletWithQuantityTable.startBulletWithQuantityTable = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.BulletTypeEnum} type
 */
survival2d.flatbuffers.BulletWithQuantityTable.addType = function(builder, type) {
  builder.addFieldInt8(0, type, survival2d.flatbuffers.BulletTypeEnum.NORMAL);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} num
 */
survival2d.flatbuffers.BulletWithQuantityTable.addNum = function(builder, num) {
  builder.addFieldInt32(1, num, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.BulletWithQuantityTable.endBulletWithQuantityTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.BulletTypeEnum} type
 * @param {number} num
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.BulletWithQuantityTable.createBulletWithQuantityTable = function(builder, type, num) {
  survival2d.flatbuffers.BulletWithQuantityTable.startBulletWithQuantityTable(builder);
  survival2d.flatbuffers.BulletWithQuantityTable.addType(builder, type);
  survival2d.flatbuffers.BulletWithQuantityTable.addNum(builder, num);
  return survival2d.flatbuffers.BulletWithQuantityTable.endBulletWithQuantityTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.HandTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.HandTable}
 */
survival2d.flatbuffers.HandTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.HandTable=} obj
 * @returns {survival2d.flatbuffers.HandTable}
 */
survival2d.flatbuffers.HandTable.getRootAsHandTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.HandTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.HandTable=} obj
 * @returns {survival2d.flatbuffers.HandTable}
 */
survival2d.flatbuffers.HandTable.getSizePrefixedRootAsHandTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.HandTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.HandTable.startHandTable = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.HandTable.endHandTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.HandTable.createHandTable = function(builder) {
  survival2d.flatbuffers.HandTable.startHandTable(builder);
  return survival2d.flatbuffers.HandTable.endHandTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.GunTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.GunTable}
 */
survival2d.flatbuffers.GunTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.GunTable=} obj
 * @returns {survival2d.flatbuffers.GunTable}
 */
survival2d.flatbuffers.GunTable.getRootAsGunTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.GunTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.GunTable=} obj
 * @returns {survival2d.flatbuffers.GunTable}
 */
survival2d.flatbuffers.GunTable.getSizePrefixedRootAsGunTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.GunTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {survival2d.flatbuffers.GunTypeEnum}
 */
survival2d.flatbuffers.GunTable.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {survival2d.flatbuffers.GunTypeEnum} */ (this.bb.readInt8(this.bb_pos + offset)) : survival2d.flatbuffers.GunTypeEnum.NORMAL;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.GunTable.prototype.remainBullets = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.GunTable.startGunTable = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.GunTypeEnum} type
 */
survival2d.flatbuffers.GunTable.addType = function(builder, type) {
  builder.addFieldInt8(0, type, survival2d.flatbuffers.GunTypeEnum.NORMAL);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} remainBullets
 */
survival2d.flatbuffers.GunTable.addRemainBullets = function(builder, remainBullets) {
  builder.addFieldInt32(1, remainBullets, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.GunTable.endGunTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.GunTypeEnum} type
 * @param {number} remainBullets
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.GunTable.createGunTable = function(builder, type, remainBullets) {
  survival2d.flatbuffers.GunTable.startGunTable(builder);
  survival2d.flatbuffers.GunTable.addType(builder, type);
  survival2d.flatbuffers.GunTable.addRemainBullets(builder, remainBullets);
  return survival2d.flatbuffers.GunTable.endGunTable(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.WeaponTable = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.WeaponTable}
 */
survival2d.flatbuffers.WeaponTable.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.WeaponTable=} obj
 * @returns {survival2d.flatbuffers.WeaponTable}
 */
survival2d.flatbuffers.WeaponTable.getRootAsWeaponTable = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.WeaponTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.WeaponTable=} obj
 * @returns {survival2d.flatbuffers.WeaponTable}
 */
survival2d.flatbuffers.WeaponTable.getSizePrefixedRootAsWeaponTable = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.WeaponTable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {survival2d.flatbuffers.WeaponUnion}
 */
survival2d.flatbuffers.WeaponTable.prototype.dataType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {survival2d.flatbuffers.WeaponUnion} */ (this.bb.readUint8(this.bb_pos + offset)) : survival2d.flatbuffers.WeaponUnion.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
survival2d.flatbuffers.WeaponTable.prototype.data = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.WeaponTable.startWeaponTable = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.WeaponUnion} dataType
 */
survival2d.flatbuffers.WeaponTable.addDataType = function(builder, dataType) {
  builder.addFieldInt8(0, dataType, survival2d.flatbuffers.WeaponUnion.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 */
survival2d.flatbuffers.WeaponTable.addData = function(builder, dataOffset) {
  builder.addFieldOffset(1, dataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.WeaponTable.endWeaponTable = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.WeaponUnion} dataType
 * @param {flatbuffers.Offset} dataOffset
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.WeaponTable.createWeaponTable = function(builder, dataType, dataOffset) {
  survival2d.flatbuffers.WeaponTable.startWeaponTable(builder);
  survival2d.flatbuffers.WeaponTable.addDataType(builder, dataType);
  survival2d.flatbuffers.WeaponTable.addData(builder, dataOffset);
  return survival2d.flatbuffers.WeaponTable.endWeaponTable(builder);
}

// Exports for Node.js and RequireJS
this.survival2d = survival2d;
