// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var survival2d = survival2d || {};

/**
 * @const
 * @namespace
 */
survival2d.flatbuffers = survival2d.flatbuffers || {};

/**
 * @enum {number}
 */
survival2d.flatbuffers.RequestUnion = {
  NONE: 0,
  LoginRequest: 1,
  GetUserInfoRequest: 2,
  CreateTeamRequest: 3,
  JoinTeamRequest: 4,
  FindMatchRequest: 5,
  GetConfigRequest: 6,
  MatchInfoRequest: 7,
  PlayerMoveRequest: 8,
  PlayerAttackRequest: 9,
  PlayerReloadWeaponRequest: 10,
  PlayerChangeWeaponRequest: 11,
  PlayerTakeItemRequest: 12,
  SetAutoPlayRequest: 13,
  PingRequest: 14,
  PingByPlayerMoveRequest: 15,
  PingByMatchInfoRequest: 16
};

/**
 * @enum {string}
 */
survival2d.flatbuffers.RequestUnionName = {
  '0': 'NONE',
  '1': 'LoginRequest',
  '2': 'GetUserInfoRequest',
  '3': 'CreateTeamRequest',
  '4': 'JoinTeamRequest',
  '5': 'FindMatchRequest',
  '6': 'GetConfigRequest',
  '7': 'MatchInfoRequest',
  '8': 'PlayerMoveRequest',
  '9': 'PlayerAttackRequest',
  '10': 'PlayerReloadWeaponRequest',
  '11': 'PlayerChangeWeaponRequest',
  '12': 'PlayerTakeItemRequest',
  '13': 'SetAutoPlayRequest',
  '14': 'PingRequest',
  '15': 'PingByPlayerMoveRequest',
  '16': 'PingByMatchInfoRequest'
};

/**
 * @constructor
 */
survival2d.flatbuffers.LoginRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.LoginRequest}
 */
survival2d.flatbuffers.LoginRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.LoginRequest=} obj
 * @returns {survival2d.flatbuffers.LoginRequest}
 */
survival2d.flatbuffers.LoginRequest.getRootAsLoginRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.LoginRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.LoginRequest=} obj
 * @returns {survival2d.flatbuffers.LoginRequest}
 */
survival2d.flatbuffers.LoginRequest.getSizePrefixedRootAsLoginRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.LoginRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
survival2d.flatbuffers.LoginRequest.prototype.userName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.LoginRequest.startLoginRequest = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} userNameOffset
 */
survival2d.flatbuffers.LoginRequest.addUserName = function(builder, userNameOffset) {
  builder.addFieldOffset(0, userNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.LoginRequest.endLoginRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} userNameOffset
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.LoginRequest.createLoginRequest = function(builder, userNameOffset) {
  survival2d.flatbuffers.LoginRequest.startLoginRequest(builder);
  survival2d.flatbuffers.LoginRequest.addUserName(builder, userNameOffset);
  return survival2d.flatbuffers.LoginRequest.endLoginRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.GetUserInfoRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.GetUserInfoRequest}
 */
survival2d.flatbuffers.GetUserInfoRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.GetUserInfoRequest=} obj
 * @returns {survival2d.flatbuffers.GetUserInfoRequest}
 */
survival2d.flatbuffers.GetUserInfoRequest.getRootAsGetUserInfoRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.GetUserInfoRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.GetUserInfoRequest=} obj
 * @returns {survival2d.flatbuffers.GetUserInfoRequest}
 */
survival2d.flatbuffers.GetUserInfoRequest.getSizePrefixedRootAsGetUserInfoRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.GetUserInfoRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.GetUserInfoRequest.startGetUserInfoRequest = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.GetUserInfoRequest.endGetUserInfoRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.GetUserInfoRequest.createGetUserInfoRequest = function(builder) {
  survival2d.flatbuffers.GetUserInfoRequest.startGetUserInfoRequest(builder);
  return survival2d.flatbuffers.GetUserInfoRequest.endGetUserInfoRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.CreateTeamRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.CreateTeamRequest}
 */
survival2d.flatbuffers.CreateTeamRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.CreateTeamRequest=} obj
 * @returns {survival2d.flatbuffers.CreateTeamRequest}
 */
survival2d.flatbuffers.CreateTeamRequest.getRootAsCreateTeamRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.CreateTeamRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.CreateTeamRequest=} obj
 * @returns {survival2d.flatbuffers.CreateTeamRequest}
 */
survival2d.flatbuffers.CreateTeamRequest.getSizePrefixedRootAsCreateTeamRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.CreateTeamRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.CreateTeamRequest.startCreateTeamRequest = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.CreateTeamRequest.endCreateTeamRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.CreateTeamRequest.createCreateTeamRequest = function(builder) {
  survival2d.flatbuffers.CreateTeamRequest.startCreateTeamRequest(builder);
  return survival2d.flatbuffers.CreateTeamRequest.endCreateTeamRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.JoinTeamRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.JoinTeamRequest}
 */
survival2d.flatbuffers.JoinTeamRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.JoinTeamRequest=} obj
 * @returns {survival2d.flatbuffers.JoinTeamRequest}
 */
survival2d.flatbuffers.JoinTeamRequest.getRootAsJoinTeamRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.JoinTeamRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.JoinTeamRequest=} obj
 * @returns {survival2d.flatbuffers.JoinTeamRequest}
 */
survival2d.flatbuffers.JoinTeamRequest.getSizePrefixedRootAsJoinTeamRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.JoinTeamRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.JoinTeamRequest.prototype.teamId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.JoinTeamRequest.startJoinTeamRequest = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} teamId
 */
survival2d.flatbuffers.JoinTeamRequest.addTeamId = function(builder, teamId) {
  builder.addFieldInt32(0, teamId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.JoinTeamRequest.endJoinTeamRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} teamId
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.JoinTeamRequest.createJoinTeamRequest = function(builder, teamId) {
  survival2d.flatbuffers.JoinTeamRequest.startJoinTeamRequest(builder);
  survival2d.flatbuffers.JoinTeamRequest.addTeamId(builder, teamId);
  return survival2d.flatbuffers.JoinTeamRequest.endJoinTeamRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.FindMatchRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.FindMatchRequest}
 */
survival2d.flatbuffers.FindMatchRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.FindMatchRequest=} obj
 * @returns {survival2d.flatbuffers.FindMatchRequest}
 */
survival2d.flatbuffers.FindMatchRequest.getRootAsFindMatchRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.FindMatchRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.FindMatchRequest=} obj
 * @returns {survival2d.flatbuffers.FindMatchRequest}
 */
survival2d.flatbuffers.FindMatchRequest.getSizePrefixedRootAsFindMatchRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.FindMatchRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.FindMatchRequest.startFindMatchRequest = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.FindMatchRequest.endFindMatchRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.FindMatchRequest.createFindMatchRequest = function(builder) {
  survival2d.flatbuffers.FindMatchRequest.startFindMatchRequest(builder);
  return survival2d.flatbuffers.FindMatchRequest.endFindMatchRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.GetConfigRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.GetConfigRequest}
 */
survival2d.flatbuffers.GetConfigRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.GetConfigRequest=} obj
 * @returns {survival2d.flatbuffers.GetConfigRequest}
 */
survival2d.flatbuffers.GetConfigRequest.getRootAsGetConfigRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.GetConfigRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.GetConfigRequest=} obj
 * @returns {survival2d.flatbuffers.GetConfigRequest}
 */
survival2d.flatbuffers.GetConfigRequest.getSizePrefixedRootAsGetConfigRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.GetConfigRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.GetConfigRequest.startGetConfigRequest = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.GetConfigRequest.endGetConfigRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.GetConfigRequest.createGetConfigRequest = function(builder) {
  survival2d.flatbuffers.GetConfigRequest.startGetConfigRequest(builder);
  return survival2d.flatbuffers.GetConfigRequest.endGetConfigRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.MatchInfoRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.MatchInfoRequest}
 */
survival2d.flatbuffers.MatchInfoRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.MatchInfoRequest=} obj
 * @returns {survival2d.flatbuffers.MatchInfoRequest}
 */
survival2d.flatbuffers.MatchInfoRequest.getRootAsMatchInfoRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.MatchInfoRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.MatchInfoRequest=} obj
 * @returns {survival2d.flatbuffers.MatchInfoRequest}
 */
survival2d.flatbuffers.MatchInfoRequest.getSizePrefixedRootAsMatchInfoRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.MatchInfoRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.MatchInfoRequest.startMatchInfoRequest = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.MatchInfoRequest.endMatchInfoRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.MatchInfoRequest.createMatchInfoRequest = function(builder) {
  survival2d.flatbuffers.MatchInfoRequest.startMatchInfoRequest(builder);
  return survival2d.flatbuffers.MatchInfoRequest.endMatchInfoRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.PlayerMoveRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.PlayerMoveRequest}
 */
survival2d.flatbuffers.PlayerMoveRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PlayerMoveRequest=} obj
 * @returns {survival2d.flatbuffers.PlayerMoveRequest}
 */
survival2d.flatbuffers.PlayerMoveRequest.getRootAsPlayerMoveRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.PlayerMoveRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PlayerMoveRequest=} obj
 * @returns {survival2d.flatbuffers.PlayerMoveRequest}
 */
survival2d.flatbuffers.PlayerMoveRequest.getSizePrefixedRootAsPlayerMoveRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.PlayerMoveRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {survival2d.flatbuffers.Vector2Struct=} obj
 * @returns {survival2d.flatbuffers.Vector2Struct|null}
 */
survival2d.flatbuffers.PlayerMoveRequest.prototype.direction = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new survival2d.flatbuffers.Vector2Struct).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.PlayerMoveRequest.prototype.rotation = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.PlayerMoveRequest.startPlayerMoveRequest = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} directionOffset
 */
survival2d.flatbuffers.PlayerMoveRequest.addDirection = function(builder, directionOffset) {
  builder.addFieldStruct(0, directionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} rotation
 */
survival2d.flatbuffers.PlayerMoveRequest.addRotation = function(builder, rotation) {
  builder.addFieldFloat32(1, rotation, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PlayerMoveRequest.endPlayerMoveRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} directionOffset
 * @param {number} rotation
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PlayerMoveRequest.createPlayerMoveRequest = function(builder, directionOffset, rotation) {
  survival2d.flatbuffers.PlayerMoveRequest.startPlayerMoveRequest(builder);
  survival2d.flatbuffers.PlayerMoveRequest.addDirection(builder, directionOffset);
  survival2d.flatbuffers.PlayerMoveRequest.addRotation(builder, rotation);
  return survival2d.flatbuffers.PlayerMoveRequest.endPlayerMoveRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.PlayerChangeWeaponRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.PlayerChangeWeaponRequest}
 */
survival2d.flatbuffers.PlayerChangeWeaponRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PlayerChangeWeaponRequest=} obj
 * @returns {survival2d.flatbuffers.PlayerChangeWeaponRequest}
 */
survival2d.flatbuffers.PlayerChangeWeaponRequest.getRootAsPlayerChangeWeaponRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.PlayerChangeWeaponRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PlayerChangeWeaponRequest=} obj
 * @returns {survival2d.flatbuffers.PlayerChangeWeaponRequest}
 */
survival2d.flatbuffers.PlayerChangeWeaponRequest.getSizePrefixedRootAsPlayerChangeWeaponRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.PlayerChangeWeaponRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.PlayerChangeWeaponRequest.prototype.slot = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.PlayerChangeWeaponRequest.startPlayerChangeWeaponRequest = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} slot
 */
survival2d.flatbuffers.PlayerChangeWeaponRequest.addSlot = function(builder, slot) {
  builder.addFieldInt8(0, slot, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PlayerChangeWeaponRequest.endPlayerChangeWeaponRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} slot
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PlayerChangeWeaponRequest.createPlayerChangeWeaponRequest = function(builder, slot) {
  survival2d.flatbuffers.PlayerChangeWeaponRequest.startPlayerChangeWeaponRequest(builder);
  survival2d.flatbuffers.PlayerChangeWeaponRequest.addSlot(builder, slot);
  return survival2d.flatbuffers.PlayerChangeWeaponRequest.endPlayerChangeWeaponRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.PlayerAttackRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.PlayerAttackRequest}
 */
survival2d.flatbuffers.PlayerAttackRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PlayerAttackRequest=} obj
 * @returns {survival2d.flatbuffers.PlayerAttackRequest}
 */
survival2d.flatbuffers.PlayerAttackRequest.getRootAsPlayerAttackRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.PlayerAttackRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PlayerAttackRequest=} obj
 * @returns {survival2d.flatbuffers.PlayerAttackRequest}
 */
survival2d.flatbuffers.PlayerAttackRequest.getSizePrefixedRootAsPlayerAttackRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.PlayerAttackRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.PlayerAttackRequest.startPlayerAttackRequest = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PlayerAttackRequest.endPlayerAttackRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PlayerAttackRequest.createPlayerAttackRequest = function(builder) {
  survival2d.flatbuffers.PlayerAttackRequest.startPlayerAttackRequest(builder);
  return survival2d.flatbuffers.PlayerAttackRequest.endPlayerAttackRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.PlayerReloadWeaponRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.PlayerReloadWeaponRequest}
 */
survival2d.flatbuffers.PlayerReloadWeaponRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PlayerReloadWeaponRequest=} obj
 * @returns {survival2d.flatbuffers.PlayerReloadWeaponRequest}
 */
survival2d.flatbuffers.PlayerReloadWeaponRequest.getRootAsPlayerReloadWeaponRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.PlayerReloadWeaponRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PlayerReloadWeaponRequest=} obj
 * @returns {survival2d.flatbuffers.PlayerReloadWeaponRequest}
 */
survival2d.flatbuffers.PlayerReloadWeaponRequest.getSizePrefixedRootAsPlayerReloadWeaponRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.PlayerReloadWeaponRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.PlayerReloadWeaponRequest.startPlayerReloadWeaponRequest = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PlayerReloadWeaponRequest.endPlayerReloadWeaponRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PlayerReloadWeaponRequest.createPlayerReloadWeaponRequest = function(builder) {
  survival2d.flatbuffers.PlayerReloadWeaponRequest.startPlayerReloadWeaponRequest(builder);
  return survival2d.flatbuffers.PlayerReloadWeaponRequest.endPlayerReloadWeaponRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.PlayerTakeItemRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.PlayerTakeItemRequest}
 */
survival2d.flatbuffers.PlayerTakeItemRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PlayerTakeItemRequest=} obj
 * @returns {survival2d.flatbuffers.PlayerTakeItemRequest}
 */
survival2d.flatbuffers.PlayerTakeItemRequest.getRootAsPlayerTakeItemRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.PlayerTakeItemRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PlayerTakeItemRequest=} obj
 * @returns {survival2d.flatbuffers.PlayerTakeItemRequest}
 */
survival2d.flatbuffers.PlayerTakeItemRequest.getSizePrefixedRootAsPlayerTakeItemRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.PlayerTakeItemRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.PlayerTakeItemRequest.startPlayerTakeItemRequest = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PlayerTakeItemRequest.endPlayerTakeItemRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PlayerTakeItemRequest.createPlayerTakeItemRequest = function(builder) {
  survival2d.flatbuffers.PlayerTakeItemRequest.startPlayerTakeItemRequest(builder);
  return survival2d.flatbuffers.PlayerTakeItemRequest.endPlayerTakeItemRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.SetAutoPlayRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.SetAutoPlayRequest}
 */
survival2d.flatbuffers.SetAutoPlayRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.SetAutoPlayRequest=} obj
 * @returns {survival2d.flatbuffers.SetAutoPlayRequest}
 */
survival2d.flatbuffers.SetAutoPlayRequest.getRootAsSetAutoPlayRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.SetAutoPlayRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.SetAutoPlayRequest=} obj
 * @returns {survival2d.flatbuffers.SetAutoPlayRequest}
 */
survival2d.flatbuffers.SetAutoPlayRequest.getSizePrefixedRootAsSetAutoPlayRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.SetAutoPlayRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {boolean}
 */
survival2d.flatbuffers.SetAutoPlayRequest.prototype.enable = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.SetAutoPlayRequest.startSetAutoPlayRequest = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} enable
 */
survival2d.flatbuffers.SetAutoPlayRequest.addEnable = function(builder, enable) {
  builder.addFieldInt8(0, +enable, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.SetAutoPlayRequest.endSetAutoPlayRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} enable
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.SetAutoPlayRequest.createSetAutoPlayRequest = function(builder, enable) {
  survival2d.flatbuffers.SetAutoPlayRequest.startSetAutoPlayRequest(builder);
  survival2d.flatbuffers.SetAutoPlayRequest.addEnable(builder, enable);
  return survival2d.flatbuffers.SetAutoPlayRequest.endSetAutoPlayRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.PingRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.PingRequest}
 */
survival2d.flatbuffers.PingRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PingRequest=} obj
 * @returns {survival2d.flatbuffers.PingRequest}
 */
survival2d.flatbuffers.PingRequest.getRootAsPingRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.PingRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PingRequest=} obj
 * @returns {survival2d.flatbuffers.PingRequest}
 */
survival2d.flatbuffers.PingRequest.getSizePrefixedRootAsPingRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.PingRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.PingRequest.startPingRequest = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PingRequest.endPingRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PingRequest.createPingRequest = function(builder) {
  survival2d.flatbuffers.PingRequest.startPingRequest(builder);
  return survival2d.flatbuffers.PingRequest.endPingRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.PingByPlayerMoveRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.PingByPlayerMoveRequest}
 */
survival2d.flatbuffers.PingByPlayerMoveRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PingByPlayerMoveRequest=} obj
 * @returns {survival2d.flatbuffers.PingByPlayerMoveRequest}
 */
survival2d.flatbuffers.PingByPlayerMoveRequest.getRootAsPingByPlayerMoveRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.PingByPlayerMoveRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PingByPlayerMoveRequest=} obj
 * @returns {survival2d.flatbuffers.PingByPlayerMoveRequest}
 */
survival2d.flatbuffers.PingByPlayerMoveRequest.getSizePrefixedRootAsPingByPlayerMoveRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.PingByPlayerMoveRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {survival2d.flatbuffers.Vector2Struct=} obj
 * @returns {survival2d.flatbuffers.Vector2Struct|null}
 */
survival2d.flatbuffers.PingByPlayerMoveRequest.prototype.direction = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new survival2d.flatbuffers.Vector2Struct).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
survival2d.flatbuffers.PingByPlayerMoveRequest.prototype.rotation = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.PingByPlayerMoveRequest.startPingByPlayerMoveRequest = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} directionOffset
 */
survival2d.flatbuffers.PingByPlayerMoveRequest.addDirection = function(builder, directionOffset) {
  builder.addFieldStruct(0, directionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} rotation
 */
survival2d.flatbuffers.PingByPlayerMoveRequest.addRotation = function(builder, rotation) {
  builder.addFieldFloat64(1, rotation, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PingByPlayerMoveRequest.endPingByPlayerMoveRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} directionOffset
 * @param {number} rotation
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PingByPlayerMoveRequest.createPingByPlayerMoveRequest = function(builder, directionOffset, rotation) {
  survival2d.flatbuffers.PingByPlayerMoveRequest.startPingByPlayerMoveRequest(builder);
  survival2d.flatbuffers.PingByPlayerMoveRequest.addDirection(builder, directionOffset);
  survival2d.flatbuffers.PingByPlayerMoveRequest.addRotation(builder, rotation);
  return survival2d.flatbuffers.PingByPlayerMoveRequest.endPingByPlayerMoveRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.PingByMatchInfoRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.PingByMatchInfoRequest}
 */
survival2d.flatbuffers.PingByMatchInfoRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PingByMatchInfoRequest=} obj
 * @returns {survival2d.flatbuffers.PingByMatchInfoRequest}
 */
survival2d.flatbuffers.PingByMatchInfoRequest.getRootAsPingByMatchInfoRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.PingByMatchInfoRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.PingByMatchInfoRequest=} obj
 * @returns {survival2d.flatbuffers.PingByMatchInfoRequest}
 */
survival2d.flatbuffers.PingByMatchInfoRequest.getSizePrefixedRootAsPingByMatchInfoRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.PingByMatchInfoRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.PingByMatchInfoRequest.startPingByMatchInfoRequest = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PingByMatchInfoRequest.endPingByMatchInfoRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.PingByMatchInfoRequest.createPingByMatchInfoRequest = function(builder) {
  survival2d.flatbuffers.PingByMatchInfoRequest.startPingByMatchInfoRequest(builder);
  return survival2d.flatbuffers.PingByMatchInfoRequest.endPingByMatchInfoRequest(builder);
}

/**
 * @constructor
 */
survival2d.flatbuffers.Request = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {survival2d.flatbuffers.Request}
 */
survival2d.flatbuffers.Request.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.Request=} obj
 * @returns {survival2d.flatbuffers.Request}
 */
survival2d.flatbuffers.Request.getRootAsRequest = function(bb, obj) {
  return (obj || new survival2d.flatbuffers.Request).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {survival2d.flatbuffers.Request=} obj
 * @returns {survival2d.flatbuffers.Request}
 */
survival2d.flatbuffers.Request.getSizePrefixedRootAsRequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new survival2d.flatbuffers.Request).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {survival2d.flatbuffers.RequestUnion}
 */
survival2d.flatbuffers.Request.prototype.requestType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {survival2d.flatbuffers.RequestUnion} */ (this.bb.readUint8(this.bb_pos + offset)) : survival2d.flatbuffers.RequestUnion.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
survival2d.flatbuffers.Request.prototype.request = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
survival2d.flatbuffers.Request.startRequest = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.RequestUnion} requestType
 */
survival2d.flatbuffers.Request.addRequestType = function(builder, requestType) {
  builder.addFieldInt8(0, requestType, survival2d.flatbuffers.RequestUnion.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} requestOffset
 */
survival2d.flatbuffers.Request.addRequest = function(builder, requestOffset) {
  builder.addFieldOffset(1, requestOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.Request.endRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
survival2d.flatbuffers.Request.finishRequestBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
survival2d.flatbuffers.Request.finishSizePrefixedRequestBuffer = function(builder, offset) {
  builder.finish(offset, undefined, true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {survival2d.flatbuffers.RequestUnion} requestType
 * @param {flatbuffers.Offset} requestOffset
 * @returns {flatbuffers.Offset}
 */
survival2d.flatbuffers.Request.createRequest = function(builder, requestType, requestOffset) {
  survival2d.flatbuffers.Request.startRequest(builder);
  survival2d.flatbuffers.Request.addRequestType(builder, requestType);
  survival2d.flatbuffers.Request.addRequest(builder, requestOffset);
  return survival2d.flatbuffers.Request.endRequest(builder);
}

// Exports for Node.js and RequireJS
this.survival2d = survival2d;
